//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RafCalc {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class CalcStr {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal CalcStr() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RafCalc.Resources.CalcStr", typeof(CalcStr).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Apprêt.
		/// </summary>
		public static string Appret {
			get {
				return ResourceManager.GetString("Appret", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Autolyse.
		/// </summary>
		public static string Autolyse {
			get {
				return ResourceManager.GetString("Autolyse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Calcul.
		/// </summary>
		public static string Calcul {
			get {
				return ResourceManager.GetString("Calcul", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le coefficient de calcul doit être compris entre 10 et 100.
		/// </summary>
		public static string CoefCalcEntre10_100 {
			get {
				return ResourceManager.GetString("CoefCalcEntre10_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le coefficient de calcul doit être compris entre 100 et 6000.
		/// </summary>
		public static string CoefCalcEntre100_6000 {
			get {
				return ResourceManager.GetString("CoefCalcEntre100_6000", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cuisson.
		/// </summary>
		public static string Cuisson {
			get {
				return ResourceManager.GetString("Cuisson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vous devez diminuer le % de farine ou le % d&apos;eau (Biga).
		/// </summary>
		public static string DiminuerPcFarineEauBiga {
			get {
				return ResourceManager.GetString("DiminuerPcFarineEauBiga", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vous devez diminuer le % de farine ou le % d&apos;eau (Poolish).
		/// </summary>
		public static string DiminuerPcFarineEauPool {
			get {
				return ResourceManager.GetString("DiminuerPcFarineEauPool", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vous devez diminuer le % de farine ou le % de sel.
		/// </summary>
		public static string DiminuerPcFarineSel {
			get {
				return ResourceManager.GetString("DiminuerPcFarineSel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Vous devez diminuer le % de farine ou le % de sel (Poolish).
		/// </summary>
		public static string DiminuerPcFarineSelPool {
			get {
				return ResourceManager.GetString("DiminuerPcFarineSelPool", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Durée de maturation conseillée:.
		/// </summary>
		public static string DurataMaturConsigliata {
			get {
				return ResourceManager.GetString("DurataMaturConsigliata", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La durée de (autolyse, biga ou poolish) doit être comprise entre 0 et 48h.
		/// </summary>
		public static string DureeAutoBigaPoolishEntre0_48 {
			get {
				return ResourceManager.GetString("DureeAutoBigaPoolishEntre0_48", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La durée de pétrissage doit être comprise entre 0 et 99 min.
		/// </summary>
		public static string DureePetrissEntre0_99 {
			get {
				return ResourceManager.GetString("DureePetrissEntre0_99", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Durée Totale.
		/// </summary>
		public static string DureeTotale {
			get {
				return ResourceManager.GetString("DureeTotale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La durée totale de maturation doit être comprise entre 3h et 96h.
		/// </summary>
		public static string DureeTotMaturEntre3_96 {
			get {
				return ResourceManager.GetString("DureeTotMaturEntre3_96", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Eau.
		/// </summary>
		public static string Eau {
			get {
				return ResourceManager.GetString("Eau", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Erreur sur heures d&apos;apprêt dans les phases TA-Frigo.
		/// </summary>
		public static string ErreurHeuresAppretTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresAppretTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Erreur sur heures de frigo dans les phases TA-Frigo.
		/// </summary>
		public static string ErreurHeuresFrigoTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresFrigoTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Erreur sur heures de pointage dans les phases TA-Frigo.
		/// </summary>
		public static string ErreurHeuresPointageTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresPointageTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Farine.
		/// </summary>
		public static string Farine {
			get {
				return ResourceManager.GetString("Farine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Force farine indicative conseillée: W ≈ {0} (équivalent protéines ≈ {1}).
		/// </summary>
		public static string ForceFarineConseillee {
			get {
				return ResourceManager.GetString("ForceFarineConseillee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Les heures de frigo ne doivent pas dépasser le total des heures -1.
		/// </summary>
		public static string HeureFriNoSupTotalHeure {
			get {
				return ResourceManager.GetString("HeureFriNoSupTotalHeure", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Horaires.
		/// </summary>
		public static string Horaires {
			get {
				return ResourceManager.GetString("Horaires", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Huile.
		/// </summary>
		public static string Huile {
			get {
				return ResourceManager.GetString("Huile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Infos.
		/// </summary>
		public static string Infos {
			get {
				return ResourceManager.GetString("Infos", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Ingrédients.
		/// </summary>
		public static string Ingredients {
			get {
				return ResourceManager.GetString("Ingredients", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Levure.
		/// </summary>
		public static string Levure {
			get {
				return ResourceManager.GetString("Levure", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Mix Eaux.
		/// </summary>
		public static string MixEaux {
			get {
				return ResourceManager.GetString("MixEaux", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Mix Farines.
		/// </summary>
		public static string MixFarines {
			get {
				return ResourceManager.GetString("MixFarines", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Veuillez définir un nombre de pâtons &gt; 0.
		/// </summary>
		public static string NbePatonsPositifRequis {
			get {
				return ResourceManager.GetString("NbePatonsPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pâtons.
		/// </summary>
		public static string Patons {
			get {
				return ResourceManager.GetString("Patons", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le pourcentage d&apos;hydratation doit être compris entre 50% et 100%.
		/// </summary>
		public static string PcHydratEntre50_100 {
			get {
				return ResourceManager.GetString("PcHydratEntre50_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Chaque % d&apos;ingrédient de (autolyse, biga ou poolish) doit être compris entre 0 et 100%.
		/// </summary>
		public static string PcIngredAutoBigaPoolEntre0_100 {
			get {
				return ResourceManager.GetString("PcIngredAutoBigaPoolEntre0_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pétrissage.
		/// </summary>
		public static string Petrissage {
			get {
				return ResourceManager.GetString("Petrissage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le poids de l&apos;eau doit être &gt; 0.
		/// </summary>
		public static string PoidsEauPositifRequis {
			get {
				return ResourceManager.GetString("PoidsEauPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le poids de la farine doit être &gt; 0.
		/// </summary>
		public static string PoidsFarinePositifRequis {
			get {
				return ResourceManager.GetString("PoidsFarinePositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Veuillez définir un poids de pâton &gt; 0.
		/// </summary>
		public static string PoidsPatonPositifRequis {
			get {
				return ResourceManager.GetString("PoidsPatonPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Poids total.
		/// </summary>
		public static string PoidsTotal {
			get {
				return ResourceManager.GetString("PoidsTotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Pointage.
		/// </summary>
		public static string Pointage {
			get {
				return ResourceManager.GetString("Pointage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Les quantités de calcium et magnesium doivent être comprises entre 0 et 1000.
		/// </summary>
		public static string QteCaMgEntre0_1000 {
			get {
				return ResourceManager.GetString("QteCaMgEntre0_1000", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sel.
		/// </summary>
		public static string Sel {
			get {
				return ResourceManager.GetString("Sel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le taux d&apos;huile/litre doit être compris entre 0 et 60.
		/// </summary>
		public static string TauxHuilelitreEntre0_60 {
			get {
				return ResourceManager.GetString("TauxHuilelitreEntre0_60", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le taux de sel/litre doit être compris entre 0 et 60.
		/// </summary>
		public static string TauxSellitreEntre0_60 {
			get {
				return ResourceManager.GetString("TauxSellitreEntre0_60", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La température doit être comprise entre 15°C et 35°C.
		/// </summary>
		public static string TempEntre15_35 {
			get {
				return ResourceManager.GetString("TempEntre15_35", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Température.
		/// </summary>
		public static string Temperature {
			get {
				return ResourceManager.GetString("Temperature", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le texte est trop long ({1} car max).
		/// </summary>
		public static string TexteTropLong {
			get {
				return ResourceManager.GetString("TexteTropLong", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valeur positive requise.
		/// </summary>
		public static string ValeurPosRequis {
			get {
				return ResourceManager.GetString("ValeurPosRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valeur positive &gt;0 requise.
		/// </summary>
		public static string ValeurPosSup0Requis {
			get {
				return ResourceManager.GetString("ValeurPosSup0Requis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valeur non valide ({1}-{2}).
		/// </summary>
		public static string ValNonValidPlage {
			get {
				return ResourceManager.GetString("ValNonValidPlage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Les valeurs saisies doivent être positives.
		/// </summary>
		public static string ValPositivesRequises {
			get {
				return ResourceManager.GetString("ValPositivesRequises", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to W farine doit être compris entre 90 et 450.
		/// </summary>
		public static string WFarineEntre90_450 {
			get {
				return ResourceManager.GetString("WFarineEntre90_450", resourceCulture);
			}
		}
	}
}
