//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RafCalc {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class CalcStr_it_IT {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal CalcStr_it_IT() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RafCalc.Resources.CalcStr.it-IT", typeof(CalcStr_it_IT).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Appretto.
		/// </summary>
		public static string Appret {
			get {
				return ResourceManager.GetString("Appret", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Autolisi.
		/// </summary>
		public static string Autolyse {
			get {
				return ResourceManager.GetString("Autolyse", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Calcolo.
		/// </summary>
		public static string Calcul {
			get {
				return ResourceManager.GetString("Calcul", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il coefficiente di calcolo deve essere compreso tra 10 e 100.
		/// </summary>
		public static string CoefCalcEntre10_100 {
			get {
				return ResourceManager.GetString("CoefCalcEntre10_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il coefficiente di calcolo deve essere compreso tra 100 e 6000.
		/// </summary>
		public static string CoefCalcEntre100_6000 {
			get {
				return ResourceManager.GetString("CoefCalcEntre100_6000", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cottura.
		/// </summary>
		public static string Cuisson {
			get {
				return ResourceManager.GetString("Cuisson", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bisogna ridurre la % di farina o la % di acqua (Biga).
		/// </summary>
		public static string DiminuerPcFarineEauBiga {
			get {
				return ResourceManager.GetString("DiminuerPcFarineEauBiga", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bisogna ridurre la % di farina o la % di acqua (Poolish).
		/// </summary>
		public static string DiminuerPcFarineEauPool {
			get {
				return ResourceManager.GetString("DiminuerPcFarineEauPool", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bisogna ridurre la % di farina o la % di sale.
		/// </summary>
		public static string DiminuerPcFarineSel {
			get {
				return ResourceManager.GetString("DiminuerPcFarineSel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Bisogna ridurre la % di farina o la % di sale (Poolish).
		/// </summary>
		public static string DiminuerPcFarineSelPool {
			get {
				return ResourceManager.GetString("DiminuerPcFarineSelPool", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Durata di maturazione consigliata:.
		/// </summary>
		public static string DurataMaturConsigliata {
			get {
				return ResourceManager.GetString("DurataMaturConsigliata", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La durata di (autolisi, biga o poolish) deve essere compresa tra 0 e 48h.
		/// </summary>
		public static string DureeAutoBigaPoolishEntre0_48 {
			get {
				return ResourceManager.GetString("DureeAutoBigaPoolishEntre0_48", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il tempo di impastamento deve essere compreso tra 0 e 99 min.
		/// </summary>
		public static string DureePetrissEntre0_99 {
			get {
				return ResourceManager.GetString("DureePetrissEntre0_99", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Durata Totale.
		/// </summary>
		public static string DureeTotale {
			get {
				return ResourceManager.GetString("DureeTotale", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il tempo totale di maturazione deve essere compreso tra 3h e 96h.
		/// </summary>
		public static string DureeTotMaturEntre3_96 {
			get {
				return ResourceManager.GetString("DureeTotMaturEntre3_96", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Acqua.
		/// </summary>
		public static string Eau {
			get {
				return ResourceManager.GetString("Eau", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Errori sulle ore di appretto nelle fasi TA-Frigo.
		/// </summary>
		public static string ErreurHeuresAppretTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresAppretTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Errori sulle ore di frigo nelle fasi TA-Frigo.
		/// </summary>
		public static string ErreurHeuresFrigoTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresFrigoTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Errori sulle ore di puntata nelle fasi TA-Frigo.
		/// </summary>
		public static string ErreurHeuresPointageTAFrigo {
			get {
				return ResourceManager.GetString("ErreurHeuresPointageTAFrigo", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Farina.
		/// </summary>
		public static string Farine {
			get {
				return ResourceManager.GetString("Farine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Forza farina indicativa consigliata: W ≈ {0} (proteine equivalenti ≈ {1}).
		/// </summary>
		public static string ForceFarineConseillee {
			get {
				return ResourceManager.GetString("ForceFarineConseillee", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le ore in frigo non devono superare il totale delle ore -1.
		/// </summary>
		public static string HeureFriNoSupTotalHeure {
			get {
				return ResourceManager.GetString("HeureFriNoSupTotalHeure", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Tempistiche.
		/// </summary>
		public static string Horaires {
			get {
				return ResourceManager.GetString("Horaires", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Grassi.
		/// </summary>
		public static string Huile {
			get {
				return ResourceManager.GetString("Huile", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Info.
		/// </summary>
		public static string Infos {
			get {
				return ResourceManager.GetString("Infos", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Ingredienti.
		/// </summary>
		public static string Ingredients {
			get {
				return ResourceManager.GetString("Ingredients", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Lievito.
		/// </summary>
		public static string Levure {
			get {
				return ResourceManager.GetString("Levure", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Mix Acque.
		/// </summary>
		public static string MixEaux {
			get {
				return ResourceManager.GetString("MixEaux", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Mix Farine.
		/// </summary>
		public static string MixFarines {
			get {
				return ResourceManager.GetString("MixFarines", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Definire un numero di panielli &gt; 0.
		/// </summary>
		public static string NbePatonsPositifRequis {
			get {
				return ResourceManager.GetString("NbePatonsPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Panielli.
		/// </summary>
		public static string Patons {
			get {
				return ResourceManager.GetString("Patons", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La percentuale di idratazione deve essere compresa tra 50% e 100%.
		/// </summary>
		public static string PcHydratEntre50_100 {
			get {
				return ResourceManager.GetString("PcHydratEntre50_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Ogni % di ingrediente di (autolisi, biga o poolish) deve essere compreso tra 0 e 100%.
		/// </summary>
		public static string PcIngredAutoBigaPoolEntre0_100 {
			get {
				return ResourceManager.GetString("PcIngredAutoBigaPoolEntre0_100", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Impastamento.
		/// </summary>
		public static string Petrissage {
			get {
				return ResourceManager.GetString("Petrissage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il peso dell&apos;acqua deve essere &gt; 0.
		/// </summary>
		public static string PoidsEauPositifRequis {
			get {
				return ResourceManager.GetString("PoidsEauPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il peso della farina deve essere &gt; 0.
		/// </summary>
		public static string PoidsFarinePositifRequis {
			get {
				return ResourceManager.GetString("PoidsFarinePositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Definire un peso di paniello &gt; 0.
		/// </summary>
		public static string PoidsPatonPositifRequis {
			get {
				return ResourceManager.GetString("PoidsPatonPositifRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Peso totale.
		/// </summary>
		public static string PoidsTotal {
			get {
				return ResourceManager.GetString("PoidsTotal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Puntata.
		/// </summary>
		public static string Pointage {
			get {
				return ResourceManager.GetString("Pointage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Le quantità di calcio e magnesio devono essere comprese tra 0 e 1000.
		/// </summary>
		public static string QteCaMgEntre0_1000 {
			get {
				return ResourceManager.GetString("QteCaMgEntre0_1000", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sale.
		/// </summary>
		public static string Sel {
			get {
				return ResourceManager.GetString("Sel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il livello di grassi/litro deve essere compreso tra 0 e 60.
		/// </summary>
		public static string TauxHuilelitreEntre0_60 {
			get {
				return ResourceManager.GetString("TauxHuilelitreEntre0_60", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il livello di sale/litro deve essere compreso tra 0 e 60.
		/// </summary>
		public static string TauxSellitreEntre0_60 {
			get {
				return ResourceManager.GetString("TauxSellitreEntre0_60", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to La temperatura deve essere compresa tra 15°C e 35°C.
		/// </summary>
		public static string TempEntre15_35 {
			get {
				return ResourceManager.GetString("TempEntre15_35", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Temperatura.
		/// </summary>
		public static string Temperature {
			get {
				return ResourceManager.GetString("Temperature", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Il testo è troppo lungo ({1} car max).
		/// </summary>
		public static string TexteTropLong {
			get {
				return ResourceManager.GetString("TexteTropLong", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valore positivo richiesto.
		/// </summary>
		public static string ValeurPosRequis {
			get {
				return ResourceManager.GetString("ValeurPosRequis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valore positivo &gt;0 richiesto.
		/// </summary>
		public static string ValeurPosSup0Requis {
			get {
				return ResourceManager.GetString("ValeurPosSup0Requis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Valore non valido ({1}-{2}).
		/// </summary>
		public static string ValNonValidPlage {
			get {
				return ResourceManager.GetString("ValNonValidPlage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to I valori inseriti devono essere positivi.
		/// </summary>
		public static string ValPositivesRequises {
			get {
				return ResourceManager.GetString("ValPositivesRequises", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to W farina deve essere compreso tra 90 e 450.
		/// </summary>
		public static string WFarineEntre90_450 {
			get {
				return ResourceManager.GetString("WFarineEntre90_450", resourceCulture);
			}
		}
	}
}
